In [64]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [8]:
indA = pd.Index([1,3,5,7,9])
indB = pd.Index([2,3,5,7,11])

index as ordered set

In [10]:
indA & indB #intersection

Int64Index([3, 5, 7], dtype='int64')

In [11]:
indA | indB #union

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [12]:
indA ^ indB # summetric difference

Int64Index([1, 2, 9, 11], dtype='int64')

## data selection in Series

In [15]:
data = pd.Series([0.25,0.5,0.75,1.0],
                index = list('abcd'))
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [16]:
data['b']

0.5

In [17]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [18]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

Series as one-dimensional array

In [19]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [21]:
data[(data>0.3) & (data<0.8)]

b    0.50
c    0.75
dtype: float64

In [24]:
data[['a','c']]

a    0.25
c    0.75
dtype: float64

In [26]:
data = pd.Series(list('abc'),index = range(1,6,2))
data

1    a
3    b
5    c
dtype: object

In [27]:
data[5]

'c'

the loc attribute allows indexing and slicing that always references the explicit index:

In [29]:
data.loc[5]

'c'

iloc attribute allows indexing and slicing that always references the implicit
Python-style index

In [33]:
data.iloc[2]

'c'

## Data Selection in DataFrame

In [36]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                          'New York': 141297, 'Florida': 170312,
                          'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                         'New York': 19651127, 'Florida': 19552860,
                         'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [37]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [44]:
data.loc[["California"],"area"]

California    423967
Name: area, dtype: int64

In [47]:
data.loc["California","area"]

423967

In [48]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [49]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [58]:
data.values.reshape(-1)

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01, 6.95662000e+05,
       2.64481930e+07, 3.80187404e+01, 1.41297000e+05, 1.96511270e+07,
       1.39076746e+02, 1.70312000e+05, 1.95528600e+07, 1.14806121e+02,
       1.49995000e+05, 1.28821350e+07, 8.58837628e+01])

In [61]:
data.area.values

array([423967, 695662, 141297, 170312, 149995])

In [62]:
data.iloc[:3,:2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

The $ix$ indexer allows a hybrid of these two approaches:

In [65]:
data.ix[:3,'pop']

California    38332521
Texas         26448193
New York      19651127
Name: pop, dtype: int64

Additional indexing conventions

In [73]:
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [74]:
data["Florida":"Illinois"]

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [78]:
data.iloc[:,1:3]

pop     density
California  38332521   90.413926
Texas       26448193   38.018740
New York    19651127  139.076746
Florida     19552860  114.806121
Illinois    12882135   85.883763